# PyTorch Getting Started

Welcome to your PyTorch learning environment! This notebook will help you verify that everything is working correctly.

In [ ]:
# Import essential libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")
    print(f"GPU device: {torch.cuda.get_device_name(0)}")

PyTorch version: 2.1.0
CUDA available: False


In [13]:
## Introduction to Tensors

# Create a tensor
scalar = torch.tensor(7)

print(scalar.ndim)
print(scalar.item())


0
7


In [41]:
#Vector
vector = torch.tensor([7, 7, 8], [1,2])
vector

TypeError: tensor() takes 1 positional argument but 2 were given

In [39]:
vector.ndim

1

In [40]:
vector.shape

torch.Size([3])

In [19]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

MATRIX[1]

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [43]:
#TENSER
TENSER = torch.tensor([[[[1,2,3, 4],
                        [3,6,9, 8],
                        [2,4,5, 7]]]])
TENSER

tensor([[[[1, 2, 3, 4],
          [3, 6, 9, 8],
          [2, 4, 5, 7]]]])

In [44]:
TENSER.ndim

4

In [45]:
TENSER.shape

torch.Size([1, 1, 3, 4])

In [34]:
TENSER[0]

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [56]:
# RANDOM tensors
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9052, 0.6240, 0.1243, 0.6786],
        [0.5417, 0.6392, 0.5759, 0.7318],
        [0.2621, 0.4302, 0.2637, 0.7267]])

In [57]:
random_tensor.ndim

2

In [61]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244)) # height, widht colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [64]:
# Zeros and ones
# Create a tensor of all zeors
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [78]:
# Create a range of tensors and tensors-like
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
# Floar 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                              device=None, # What device is your tensor on
                              requires_grad=False) # whether or not track gradients
float_32_tensor.dtype


torch.float32

In [87]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [88]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [91]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

In [92]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [94]:
### Getting information from tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0439, 0.3580, 0.9933, 0.8590],
        [0.8409, 0.6960, 0.9187, 0.9373],
        [0.6913, 0.0652, 0.9592, 0.2839]])

In [99]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0439, 0.3580, 0.9933, 0.8590],
        [0.8409, 0.6960, 0.9187, 0.9373],
        [0.6913, 0.0652, 0.9592, 0.2839]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [102]:
### Manipulating Tensors (tensor operations)
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [103]:
tensor * 10

tensor([10, 20, 30])

In [104]:
tensor - 10

tensor([-9, -8, -7])

In [106]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [110]:
### Matrix multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [115]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [118]:
torch.matmul(tensor, tensor)

tensor(14)

In [129]:
## Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                           [8, 11],
                           [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [134]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [135]:
### Reshaping, stacking, squeezing, and unsqueezing tensors
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [139]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [140]:
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [144]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [145]:
x_reshaped.shape

torch.Size([1, 9])

In [146]:
x_reshaped.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
x_reshaped


tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [149]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [150]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [151]:
array.dtype

dtype('float64')